# Generated by Django 2.1.5 on 2019-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opintojaksot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunniste', models.CharField(max_length=10)),
                ('koodi', models.CharField(max_length=50)),
                ('nimi', models.CharField(max_length=30)),
                ('pisteet_min', models.IntegerField()),
                ('pisteet_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='oppi_aineet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koodi', models.CharField(max_length=10)),
                ('opintojakso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='periodit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opintojakso', models.CharField(max_length=15)),
                ('periodi1', models.BooleanField(default=False)),
                ('periodi2', models.BooleanField(default=False)),
                ('periodi3', models.BooleanField(default=False)),
                ('periodi4', models.BooleanField(default=False)),
                ('periodi5', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tutkinto_ohjelmat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koodi', models.CharField(max_length=10)),
                ('opintojakso', models.CharField(max_length=10)),
            ],
        ),
    ]
