# Generated by Django 2.1.5 on 2019-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0002_auto_20190209_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opintojaksot',
            name='koodi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opintojaksot',
            name='nimi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opintojaksot',
            name='tunniste',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oppi_aineet',
            name='koodi',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oppi_aineet',
            name='opintojakso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='periodit',
            name='opintojakso',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutkinto_ohjelmat',
            name='koodi',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutkinto_ohjelmat',
            name='opintojakso',
            field=models.TextField(),
        ),
    ]
