# Generated by Django 2.1.5 on 2019-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0003_valitut_kurssit'),
    ]

    operations = [
        migrations.AddField(
            model_name='valitut_kurssit',
            name='kurssi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valitut_kurssit',
            name='periodi',
            field=models.IntegerField(null=True),
        ),
    ]
