# Generated by Django 2.1.5 on 2019-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0003_auto_20190209_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opintojaksot',
            name='koodi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='opintojaksot',
            name='tunniste',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oppi_aineet',
            name='koodi',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oppi_aineet',
            name='opintojakso',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='periodit',
            name='opintojakso',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutkinto_ohjelmat',
            name='koodi',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutkinto_ohjelmat',
            name='opintojakso',
            field=models.CharField(max_length=20),
        ),
    ]
