# Generated by Django 2.1.5 on 2019-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0004_auto_20190220_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='periodit',
        ),
        migrations.AlterModelOptions(
            name='opintojaksot',
            options={'verbose_name_plural': 'Opintojaksot'},
        ),
        migrations.AlterModelOptions(
            name='valitut_kurssit',
            options={'verbose_name_plural': 'Valitut kurssit'},
        ),
        migrations.AddField(
            model_name='opintojaksot',
            name='periodi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opintojaksot',
            name='periodi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opintojaksot',
            name='periodi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opintojaksot',
            name='periodi4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opintojaksot',
            name='periodi5',
            field=models.BooleanField(default=False),
        ),
    ]
