# Generated by Django 2.1.5 on 2019-02-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0004_auto_20190209_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opintojaksot',
            old_name='pisteet_max',
            new_name='nopat_max',
        ),
        migrations.RenameField(
            model_name='opintojaksot',
            old_name='pisteet_min',
            new_name='nopat_min',
        ),
    ]
