# Generated by Django 2.1.5 on 2019-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0005_auto_20190220_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='valitut_kurssit',
            name='opinto_vuosi',
            field=models.IntegerField(null=True),
        ),
    ]
