# Generated by Django 2.1.5 on 2019-02-22 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hops_app', '0006_valitut_kurssit_opinto_vuosi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valitut_kurssit',
            unique_together={('opiskelija', 'kurssi')},
        ),
    ]
