# Generated by Django 2.1.5 on 2019-02-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0007_auto_20190222_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opintojaksot',
            old_name='pisteet_max',
            new_name='nopast_min',
        ),
        migrations.RenameField(
            model_name='opintojaksot',
            old_name='pisteet_min',
            new_name='nopat_max',
        ),
    ]
