# Generated by Django 2.1.5 on 2019-02-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0009_auto_20190222_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opintojaksot',
            old_name='nopast_min',
            new_name='nopat_min',
        ),
    ]
