# Generated by Django 2.1.5 on 2019-02-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0011_opintojaksot_periodit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opintojaksot',
            name='periodi1',
        ),
        migrations.RemoveField(
            model_name='opintojaksot',
            name='periodi2',
        ),
        migrations.RemoveField(
            model_name='opintojaksot',
            name='periodi3',
        ),
        migrations.RemoveField(
            model_name='opintojaksot',
            name='periodi4',
        ),
        migrations.RemoveField(
            model_name='opintojaksot',
            name='periodi5',
        ),
    ]
