# Generated by Django 2.1.5 on 2019-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0012_auto_20190224_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='valitut_kurssit',
            name='kokonaisuus',
            field=models.CharField(choices=[('perusopinnot', 'perusopinnot'), ('pääaine', 'pääaine'), ('sivuaine', 'sivuaine')], max_length=20, null=True),
        ),
    ]
