# Generated by Django 2.1.5 on 2019-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0013_valitut_kurssit_kokonaisuus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valitut_kurssit',
            name='kokonaisuus',
        ),
        migrations.AddField(
            model_name='valitut_kurssit',
            name='perusopinnot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='valitut_kurssit',
            name='pääaine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='valitut_kurssit',
            name='sivuaine',
            field=models.BooleanField(null=True),
        ),
    ]
