# Generated by Django 2.1.5 on 2019-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0015_auto_20190225_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valitut_kurssit',
            name='opintokokonaisuus',
            field=models.CharField(default='täydentävät', max_length=20),
        ),
    ]
