# Generated by Django 2.1.5 on 2019-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0019_auto_20190313_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='opintojaksot',
            name='lisatiedot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
