# Generated by Django 2.1.5 on 2019-03-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0020_opintojaksot_lisatiedot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opintojaksot',
            name='lisatiedot',
        ),
        migrations.RemoveField(
            model_name='opintojaksot',
            name='oppiaine',
        ),
    ]
