# Generated by Django 2.1.5 on 2019-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops_app', '0021_auto_20190313_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='opintojaksot',
            name='oppiaine',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
